# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xcku060-ffva1156-2-e

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.cache/wt [current_project]
set_property parent.project_path /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files -quiet /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.runs/pcie3_ultrascale_0_synth_1/pcie3_ultrascale_0.dcp
set_property used_in_implementation false [get_files /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.runs/pcie3_ultrascale_0_synth_1/pcie3_ultrascale_0.dcp]
add_files -quiet /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.runs/coregen_fifo_32x128_synth_1/coregen_fifo_32x128.dcp
set_property used_in_implementation false [get_files /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.runs/coregen_fifo_32x128_synth_1/coregen_fifo_32x128.dcp]
add_files -quiet /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.runs/fifo_generator_0_synth_1/fifo_generator_0.dcp
set_property used_in_implementation false [get_files /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.runs/fifo_generator_0_synth_1/fifo_generator_0.dcp]
add_files -quiet /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.runs/fifo_generator_1_synth_1/fifo_generator_1.dcp
set_property used_in_implementation false [get_files /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.runs/fifo_generator_1_synth_1/fifo_generator_1.dcp]
add_files -quiet /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.runs/gtwizard_ultrascale_0_synth_1/gtwizard_ultrascale_0.dcp
set_property used_in_implementation false [get_files /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.runs/gtwizard_ultrascale_0_synth_1/gtwizard_ultrascale_0.dcp]
add_files -quiet /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.runs/gtwizard_ultrascale_l3_0_synth_1/gtwizard_ultrascale_l3_0.dcp
set_property used_in_implementation false [get_files /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.runs/gtwizard_ultrascale_l3_0_synth_1/gtwizard_ultrascale_l3_0.dcp]
add_files -quiet /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp]
add_files -quiet /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.runs/async_fifo144_prim_synth_1/async_fifo144_prim.dcp
set_property used_in_implementation false [get_files /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.runs/async_fifo144_prim_synth_1/async_fifo144_prim.dcp]
read_verilog {
  {/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/BasePicoDefines.v}
  {/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/PicoDefines.v}
  {/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/hmc_def.vh}
  {/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/hmc_func.h.v}
  {/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/hmc_arch.vh}
  {/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/reg_list.vh}
  {/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/hmc_cfg.vh}
  {/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/axi_defines.v}
  {/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/hmc_def.h.v}
}
set_property file_type "Verilog Header" [get_files {{/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/BasePicoDefines.v}}]
set_property file_type "Verilog Header" [get_files {{/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/PicoDefines.v}}]
set_property file_type "Verilog Header" [get_files {{/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/hmc_def.vh}}]
set_property file_type "Verilog Header" [get_files {{/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/hmc_func.h.v}}]
set_property file_type "Verilog Header" [get_files {{/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/hmc_arch.vh}}]
set_property file_type "Verilog Header" [get_files {{/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/reg_list.vh}}]
set_property file_type "Verilog Header" [get_files {{/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/hmc_cfg.vh}}]
set_property file_type "Verilog Header" [get_files {{/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/axi_defines.v}}]
set_property file_type "Verilog Header" [get_files {{/home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/Verilog Header/hmc_def.h.v}}]
read_verilog -library xil_defaultlib -sv {
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/invertImage.sv
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/gups_top.sv
}
read_verilog -library xil_defaultlib {
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/hmc_request_header.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/dual_buf.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/crc32k.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/FIFO.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/rw_channel.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/rw_channel_w_crc.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/BRAM.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/cmd_data_interface.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/fifo_512x128.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/CounterClkGen.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/Reorder.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/usr2flit.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/FlitsToParallel.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/rp_to_index.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/hmc_packet_issue.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/hmc_apply_flit_mask.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/hmc_add_rrp.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/hmc_sum_len.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/PIO_128_TX_ENGINE.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/PicoStreamOut.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/PicoStreamIn.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/StreamToPicoBus.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/TagFIFO.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/AXIBuffer.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/PCIeHdrAlignSplit.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/PIO_128_RX_ENGINE.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/StreamAXICtrl.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/PicoAXIUpsizer.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/PicoAXIDownsizer.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/flit_bram.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/old_flit_logger.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/arbiter.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/tx_port.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/rp_to_index_wrapper.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/hmc_mask_flits.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/hmc_tx_buffer.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/hmc_inject_pret.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/async_fifo144.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/rx_port.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/user_wrapper.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/gtwizard_ultrascale_v1_5_reset_synchronizer.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/hmc_i2c.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/pcie3_7x_to_v1_6.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/Stream2PicoBus.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/CardInfo32.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/SystemMonitor32.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/TestCounter32.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/PIO_EP.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/PicoStreamToAXI.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/AXIToHMC.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/PicoBusToI2C.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/hmc_soft_trainer.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/grand_central_tx.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/add_seq.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/hmc_flow_control.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/hmc_rx_retry.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/async_fifo_wrapper.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/rrp_extractor.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/rtc.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/tag_flits.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/errstat.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/grand_central_rx.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/hmc_phy_15g.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/StreamWidthConversion.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/xilinx_pcie_3_0_7vx.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/pcie_app_v6.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/PicoStreamToHMC.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/newGupsWrapper.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/debug_pll.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/picobus_to_i2c.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/hmc_node.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/PicoFramework.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/UserWrapper.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/hmc_top.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/RGBBlink.v
  /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/new/Pico_Toplevel.v
}
read_xdc /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/constrs_1/new/M510_KU060_FFVA1156_E.xdc
set_property used_in_implementation false [get_files /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/constrs_1/new/M510_KU060_FFVA1156_E.xdc]

read_xdc /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/constrs_1/new/m510_hmc.xdc
set_property used_in_implementation false [get_files /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/constrs_1/new/m510_hmc.xdc]

read_xdc /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/constrs_1/new/hmc_l3.xdc
set_property used_in_implementation false [get_files /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/constrs_1/new/hmc_l3.xdc]

read_xdc /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/constrs_1/new/m510ku060_hmc.xdc
set_property used_in_implementation false [get_files /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/constrs_1/new/m510ku060_hmc.xdc]

read_xdc -unmanaged /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/new/clocks.xdc
set_property used_in_implementation false [get_files /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/imports/new/clocks.xdc]

synth_design -top Pico_Toplevel -part xcku060-ffva1156-2-e
write_checkpoint -noxdef Pico_Toplevel.dcp
catch { report_utilization -file Pico_Toplevel_utilization_synth.rpt -pb Pico_Toplevel_utilization_synth.pb }
