# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/ip/gtwizard_ultrascale_l3_0/gtwizard_ultrascale_l3_0.xci
# IP: The module: 'gtwizard_ultrascale_l3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/ip/gtwizard_ultrascale_l3_0/synth/gtwizard_ultrascale_l3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_ultrascale_l3_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/ip/gtwizard_ultrascale_l3_0/synth/gtwizard_ultrascale_l3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_ultrascale_l3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/ip/gtwizard_ultrascale_l3_0/gtwizard_ultrascale_l3_0.xci
# IP: The module: 'gtwizard_ultrascale_l3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/ip/gtwizard_ultrascale_l3_0/synth/gtwizard_ultrascale_l3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_ultrascale_l3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/ip/gtwizard_ultrascale_l3_0/synth/gtwizard_ultrascale_l3_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_ultrascale_l3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
