# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/ip/async_fifo144_prim/async_fifo144_prim.xci
# IP: The module: 'async_fifo144_prim' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/ip/async_fifo144_prim/async_fifo144_prim/async_fifo144_prim_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo144_prim'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/ip/async_fifo144_prim/async_fifo144_prim/async_fifo144_prim.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo144_prim'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/ip/async_fifo144_prim/async_fifo144_prim_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo144_prim'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/ip/async_fifo144_prim/async_fifo144_prim.xci
# IP: The module: 'async_fifo144_prim' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/ip/async_fifo144_prim/async_fifo144_prim/async_fifo144_prim_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo144_prim'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/ip/async_fifo144_prim/async_fifo144_prim/async_fifo144_prim.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo144_prim'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/hmc/Desktop/pantho/HMC-Fresh-Copy/HMC-Fresh-Copy.srcs/sources_1/ip/async_fifo144_prim/async_fifo144_prim_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'async_fifo144_prim'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
