all: 
	mkdir -p ~/bin
	cd jpeg;make all;cd ..
	cd libim;make all;cd ..
	cd programs;make all;cd ..

clean:
	cd jpeg;make clean;cd ..
	cd libim;make clean;cd ..
	cd programs;make clean;cd ..
